#!/bin/bash
#correr antes que gaussian
input_file=$1 #Nombre del archivo
core_name=$2  #Nombre de la carpeta donde esto vive
Ox_Red=$3 #marca para saber si va a ser Ox o Red

#Eliminar comitas
sed -i 's/"//g' $input_file

dir_name=$core_name$Ox_Red
mkdir $dir_name 
# $core_name.inchm
touch > $core_name.inchm

inf=0
i=0


#Esto genera un archivo de smile para cada smile y un xyz
while read -r smile
do

     inf=$(($inf+1))
     i=$(printf "%05d" $inf)

     echo '###############################'

     mol_name=$core_name$i
     input_smile=$(echo $smile)
     echo $input_smile > $dir_name/$mol_name'_smile'
     cat $dir_name/$mol_name'_smile'

     #Lee las cargas para cada smile y hace la suma de la carga molecular
     pos=$(cat $dir_name/$mol_name'_smile' | awk -F+ '{print NF-1}') #< $core_name/$mol_name'_smile'
     neg=$(cat $dir_name/$mol_name'_smile' | awk -F- '{print NF-1}') #< $core_name/$mol_name'_smile'
     mol_charge=$(($pos - $neg))

     #Generas un archivo inicial xyz
     obabel -ismi $dir_name/$mol_name'_smile' -oxyz --gen3d -h > $dir_name/$mol_name'_coordin'.xyz

     #Hay varios archivos que dan warning en el xyz hay que arreglarlos
     sed -i "/WARNING/d" $dir_name/$mol_name'_coordin'.xyz
     
     #Luego checas los conformeros
     obconformer 50 1000 $dir_name/$mol_name'_coordin'.xyz > $dir_name/$mol_name'_coord0'.xyz

     #Hay varios archivos que dan warning en el xyz hay que arreglarlos
     sed -i "/WARNING/d" $dir_name/$mol_name'_coord0'.xyz

     #Optimizas usando el arreglo del anterior con el xyz obtenido del previo
     obminimize -ff mmff94 -sd -n 10000 $dir_name/$mol_name'_coord0'.xyz > $dir_name/$mol_name.xyz

     #Borras los temporales
     rm $dir_name/$mol_name'_coord0'.xyz
     rm $dir_name/$mol_name'_coordin'.xyz

     #Calcular la multiplicidad de la molécula
     mult1=$(multiplicity $mol_charge -2 $dir_name/$mol_name.xyz | awk '{print $3}')
     mult2=$(multiplicity $mol_charge -2 $dir_name/$mol_name.xyz | awk '{print $5}')
     mol_charge2=$(multiplicity $mol_charge -2 $dir_name/$mol_name.xyz | awk '{print $4}')
     
     echo $mol_name'  '$mol_charge'  '$mult1'  '$mol_charge2'  '$mult2
     echo $mult
     #escribe el archivo .inchm
     echo $mol_name'  '$mol_charge'  '$mult1'  '$mol_charge2'  '$mult2 >> $core_name.inchm

done < $input_file

