#!/bin/bash

charge=$1 #$(sed -n 8p $1 | awk '{print $1}')
num_e_reduction=1 #es el numero de e- que se toman para la reduccion (+) u oxidacion (-)
suma=0
file_name=$(echo $3 | grep -oP '.*(?=\.xyz)')
while read -r line
do
     element_n=$(echo $line | awk '{print $1}')
     case $element_n in
          H) atomic_n=1;;
          #He) atomic_n=2;;
          Li) atomic_n=3;;
          Be) atomic_n=4;;
          B) atomic_n=5;;
          C) atomic_n=6;;
          N) atomic_n=7;;
          O) atomic_n=8;;
          F) atomic_n=9;;
          #Ne) atomic_n=10;;
          Na) atomic_n=11;;
          Mg) atomic_n=12;;
          Al) atomic_n=13;;
          Si) atomic_n=14;;
          P) atomic_n=15;;
          S) atomic_n=16;;
          Cl) atomic_n=17;;
          #Ar) atomic_n=18;;
          K) atomic_n=19;;
          Ca) atomic_n=20;;
          #Sc) atomic_n=21;;
          #Ti) atomic_n=22;;
          #V) atomic_n=23;;
          Cr) atomic_n=24;;
          Mn) atomic_n=25;;
          Fe) atomic_n=26;;
          Co) atomic_n=27;;
          Ni) atomic_n=28;;
          Cu) atomic_n=29;;
          Zn) atomic_n=30;;
          Ga) atomic_n=31;;
          Ge) atomic_n=32;;
          As) atomic_n=33;;
          Se) atomic_n=34;;
          Br) atomic_n=35;;
          #Kr) atomic_n=36;;
          Rb) atomic_n=37;;
          Sr) atomic_n=38;;
          Y) atomic_n=39;;
          Zr) atomic_n=40;;
          Nb) atomic_n=41;;
          Mo) atomic_n=42;;
          Tc) atomic_n=43;;
          Ru) atomic_n=44;;
          Rh) atomic_n=45;;
          Pd) atomic_n=46;;
          Ag) atomic_n=47;;
          Cd) atomic_n=48;;
          In) atomic_n=49;;
          Sn) atomic_n=50;;
          Sb) atomic_n=51;;
          Te) atomic_n=52;;
          I) atomic_n=53;;
          #Xe) atomic_n=54;;
          Cs) atomic_n=55;;
          Ba) atomic_n=56;;
          #La) atomic_n=57;;
          #Ce) atomic_n=58;;
          #Pr) atomic_n=59;;
          #Nd) atomic_n=60;;
          #Pm) atomic_n=61;;
          #Sm) atomic_n=62;;
          #Eu) atomic_n=63;;
          #Gd) atomic_n=64;;
          #Tb) atomic_n=65;;
          #Dy) atomic_n=66;;
          #Ho) atomic_n=67;;
          #Er) atomic_n=68;;
          #Tm) atomic_n=69;;
          #Yb) atomic_n=70;;
          #Lu) atomic_n=71;;
          #Hf) atomic_n=72;;
          Ta) atomic_n=73;;
          W) atomic_n=74;;
          Re) atomic_n=75;;
          Os) atomic_n=76;;
          Ir) atomic_n=77;;
          Pt) atomic_n=78;;
          Au) atomic_n=79;;
          Hg) atomic_n=80;;
          Tl) atomic_n=81;;
          Pb) atomic_n=82;;
          Bi) atomic_n=83;;
          #Po) atomic_n=84;;
          #At) atomic_n=85;;
          #Rn) atomic_n=86;;
          #Fr) atomic_n=87;;
          #Ra) atomic_n=88;;
          #Ac) atomic_n=89;;
          #Th) atomic_n=90;;
          #Pa) atomic_n=91;;
          #U) atomic_n=92;;
          #Np) atomic_n=93;;
          #Pu) atomic_n=94;;
          #Am) atomic_n=95;;
          #Cm) atomic_n=96;;
          #Bk) atomic_n=97;;
          #Cf) atomic_n=98;;
          #Es) atomic_n=99;;
          #Fm) atomic_n=100;;
          #Md) atomic_n=101;;
          #No) atomic_n=102;;
          #Lr) atomic_n=103;;
          #Rf) atomic_n=104;;
          #Db) atomic_n=105;;
          #Sg) atomic_n=106;;
          #Bh) atomic_n=107;;
          #Hs) atomic_n=108;;
          #Mt) atomic_n=109;;
          #Ds) atomic_n=110;;
          #Rg) atomic_n=111;;
          #Cn) atomic_n=112;;
          #Nh) atomic_n=113;;
          #Fl) atomic_n=114;;
          #Mc) atomic_n=115;;
          #Lv) atomic_n=116;;
          #Ts) atomic_n=117;;
          #Og) atomic_n=118;;
          *) element_n=0 && atomic_n=0;;
     esac
     num_elec=$(($num_elec + $atomic_n))
     
done < $3

total_charge=$(($num_elec - $charge))
#echo $total_charge

if [ $(($total_charge % 2)) -eq 0 ]
then
     
     multiplicity=1
else
     multiplicity=2
fi

#Reduced
chargeR=$(($charge - $num_e_reduction))
total_chargeR=$(($num_elec - $chargeR))
#echo $total_charge

if [ $(($total_chargeR % 2)) -eq 0 ]
then
     
     multiplicityR=1
else
     multiplicityR=2
fi


echo $file_name' '$charge' '$multiplicity' '$chargeR' '$multiplicityR' '$num_e_reduction



#echo '-----------------------------'
#add=0
#for i in $(echo ${num_elec[@]})
#do
#     add=$(($add + $i))
#     echo $add
#done     

