#!/bin/bash

work_dir=$(pwd)
inchm_file=$1
queue=$2



while read -r line
do
     directory=$(echo $line | awk '{print $1}')           
     
     jobs_status=0     
     while [ $jobs_status -eq 0 ]
     do
          
          cd $directory
          
          for gjf_file in $(ls *.gjf)
          do
               jobs_num=$(bjobs | grep -c $USER)
               if [ "$jobs_num" -lt "5" ]
               then
                    file_name=$(echo $gjf_file | grep -oP '.*(?=\.gjf)')
                    g16run $queue $file_name 16
                    sleep 5
                    jobs_status=1
               else
                    sleep 5
                    jobs_status=0
               fi
          done
          
          cd $work_dir
          
     done

done < $inchm_file
